# Generated by Django 5.0.3 on 2024-03-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_project_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="due_date",
            field=models.DateField(),
        ),
    ]
